### ISSUE TITLE
DID Exchange - States

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#111]
Implementation of States defined in Aries DID Exchange RFC - https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange#states

**Comment by rolsonquadras** [comment]
Part of epic #42

**Comment by llorllale** [comment]
@rolsonquadras I've been thinking about this recently. Can you share a rough idea of what this state machine will look like?

**Comment by rolsonquadras** [comment]
@llorllale I haven't thought about this. I created this issue to track the RFC item on states.

**Comment by llorllale** [comment]
@rolsonquadras @talwinder50 

Here is where my head is at at the moment:

Protocols have well-defined states. This suggests that state management may be encapsulated within the protocols themselves, thereby freeing the user from having to drive it. Implementations of these state machines can be vetted via unit tests. And instead of having a bunch of "if-else" statements scattered about, the state machine would expose a single `Handle(msg)` and take care of it.

I think the current assumption is the user must handle all this "plumbing". I think it's good for users to be aware of the different states of a protocol but I think there's a possibility for this framework to provide the plumbing that will drive the state.

If we provide the protocol state machine then there's the possibility for it to execute "automatically". An example of an automatic instance could involve `did-exchange` where the user publishes a DID that everyone can connect to. But obviously not all cases are like this. A user may wish to halt the `did-exchange` protocol for any reason. This suggests the protocol state machine should accept "pre-event" handlers where the User is given the opportunity to stop the protocol's state from advancing. I can see use cases for post-event handlers as well.

**Comment by troyronda** [comment]
@llorllale Sure - the user needs to instantiate the Protocol based on a particular context. From there, the plumbing details are hidden with the Protocol instantiation.

From https://github.com/hyperledger/aries-framework-go/issues/114#issuecomment-521448032
> The state machine object would be instantiated from within the did-exchange package. There shouldn’t be a specific correlation back to the Aries framework package.

**Comment by fqutishat** [comment]
me and @talwinder50 will try to design it and break it to issues

**Comment by fqutishat** [comment]
https://github.com/hyperledger/aries-cloudagent-python/tree/master/aries_cloudagent/messaging/connections

**Comment by llorllale** [comment]
@fqutishat I'm not sure what you're trying to say.... 

I don't think I see what I mentioned above in that link.

**Comment by talwinder50** [comment]
@llorllale  https://github.com/SolarLune/gofsm/blob/master/gofsm.go we were thinking to implement something like this. Does this align with what you have in your mind. 

I am still bit skeptical about not using if and else for state machine. Can you elaborate or provide an example how handle(msg) will look alike ?

**Comment by llorllale** [comment]
@talwinder50 

> I am still bit skeptical about not using if and else for state machine. Can you elaborate or provide an example how handle(msg) will look alike ?

If-else statements will obviously be used - they should just be encapsulated by the state machine rather than have them spread out over the framework code and the user's code.

`gofsm` seems to be a generic state machine and as such allows registering steps. The state machines for each version of the Aries protocols should **not** allow registration of arbitrary states. You may or may not use `gofsm` under the hood but these "Register(name, state)" functions should not be exposed to the user.
