### ISSUE TITLE
invalid public key by localkms.ExportPubKeyBytes()

### ISSUE THREAD

**Issue by kdimak** [hyperledger/aries-framework-go#1483]
Public key export doing by `localkms.ExportPubKeyBytes()` doesn’t seem to do a full extract of the public key.

How to check: extend `TestLocalKMS_Success`, test signing/verification using `tinkcrypto`:
```
if strings.Contains(string(v), "ECDSA") || v == kms.Ed25519Type {
	pubKeyBytes, e := kmsService.ExportPubKeyBytes(keyID)
	require.Errorf(t, e, "KeyID has been rotated. An error must be returned")
	require.Empty(t, pubKeyBytes)

	pubKeyBytes, e = kmsService.ExportPubKeyBytes(newKeyID)
	require.NoError(t, e)
	require.NotEmpty(t, pubKeyBytes)

	kh, e := kmsService.PubKeyBytesToHandle(pubKeyBytes, v)
	require.NoError(t, e)
	require.NotEmpty(t, kh)

	// NEW: verify the restored public key
	c, err := tinkcrypto.New()
	require.NoError(t, err)

	msg := []byte("test message")

	msgSig, err := c.Sign(msg, newKeyHandle)
	require.NoError(t, err)

	err = c.Verify(msgSig, msg, kh)
	require.NoError(t, err)
}

```

**Comment by Baha-sk** [comment]
it does public extract, but Tink uses a key prefix in the signature linked to the internal key. 

The issue is Tink prefixes the signature with a special  prefix linked to the internal Tink key id. For raw keys, it doesn't append any key, there's a bug in Tink where for raw keys, it doesn't try to verify with a trimmed prefix from the signature. I will file an issue in Tink and push PR to fix this.

**Comment by Baha-sk** [comment]
posted a PR in Tink: https://github.com/google/tink/pull/326

I will update the KMS so we can fix importing raw bytes public keys (coming from DID documents) into keyset.Handle and successfully do Verify()
