### ISSUE TITLE
presentproof command: unable to provide a friendly name when accepting request-presentation

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#1996]
https://github.com/hyperledger/aries-framework-go/blob/8509b7ff523badf2755b9d930912a90fccb2f806/pkg/controller/command/presentproof/models.go#L91-L96

**Comment by llorllale** [comment]
Note: the presentproof `SavePresentation()` middleware assumes the `id` is always present which does not seem right: https://www.w3.org/TR/vc-data-model/#presentations-0

**Comment by soluchok** [comment]
@llorllale We do not need a friendly name when accepting request-presentation. A friendly name is needed on the Verifier side. When Verifier wants to save it. What is the purpose of having a friendly name on the Issuer side while accepting a request?

`middleware assumes the id is always present which does not seem right` - current logic works in the following way: if the name was not provided we rely on ID. If ID is empty then the protocol will fail due to the following error`presentation name is mandatory`.

To prevent protocol failure we can check the ID, if it is empty we will generate random name e.g `uuid.New().String()`. Does it make sense?

**Comment by llorllale** [comment]
@soluchok 

> We do not need a friendly name when accepting request-presentation. A friendly name is needed on the Verifier side. When Verifier wants to save it. What is the purpose of having a friendly name on the Issuer side while accepting a request?

Right. I got confused. It seems I need to `action.Continue(presentproofsvc.WithFriendlyNames(<myName>))`.

> To prevent protocol failure we can check the ID, if it is empty we will generate random name e.g uuid.New().String(). Does it make sense?

Sounds right.
