### ISSUE TITLE
Verifiable Credentials Data Model v1.1

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#3356]
Analyze aries `verifiable` package with [Verifiable Credentials Data Model v1.1 ](https://www.w3.org/TR/vc-data-model/) to identify, list the missing implementations and implement them.

**Comment by Abdulbois** [comment]
**Summary**

There was minor changes:

1. Dates, such as `issuanceDate` and `expirationDate`, are now[ XMLSCHEMA11-2](https://www.w3.org/TR/xmlschema11-2/#dateTime) instead of [RFC3339](https://www.ietf.org/rfc/rfc3339.txt)
-  But required specification of both sources are the same (currently codebase fully supports both specs). So there is no need to do any changes

2. The id property of the `status` and `refreshService` properties may be a URI, not just a URL

- In codebase URI is used while validating json schema. So there is no need to do any changes

3. Compliance of new zero-knowledge proof schemes, such as BBS+ is enabled

- Credential with BBS+ signature type also supported. So there is no need to do any changes

**Comment by sudeshrshetty** [comment]
closing this issue since aries already covering credential data model v1.1 changes
