### ISSUE TITLE
Move JWE crypter crypto operations under wallet

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-framework-go#385]
To ensure the wallet maintains control over secrets, the crypto operations in Crypters need to be inside the wallet. However, the formatting of envelopes doesn't conceptually belong to the wallet, and Crypters/Packers should instead ask the wallet to compute crypto operations needed for pack/unpack.

This issue is for refactoring the JWE Authcrypter.

Part of #36

**Comment by Baha-sk** [comment]
Follow up:

Since the formatting of the envelope is tightly intertwined with the encryption, the logic for formatting will be kept in the crypter.

The wallet should only handle manipulation of keys (especially the private keys) within its boundary.

therefore, operations that deal with private keys should be moved to the wallet. It has been found that only DeriveKEK is manipulating private keys and so it will be moved to the wallet.

Pack/Unpack message functions will be moved from the wallet to their own `envelope` packager under `Packager` interface.
