### ISSUE TITLE
Webhook - Support "/connections"

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#540]
Pairwise Connection Record Updated - https://github.com/hyperledger/aries-cloudagent-python/blob/master/AdminAPI.md#pairwise-connection-record-updated-connections

**Comment by DRK3** [comment]
Figure out if we need to support this from https://github.com/hyperledger/aries-cloudagent-python/blob/master/AdminAPI.md#administration-api-webhooks. There is currently a struct defined in payloads.go with this structure that has a TODO above it. If it turns out that we don't need it, then delete it.

**Comment by rolsonquadras** [comment]
This will be done as part of #551 .
