### ISSUE TITLE
REST accept-invitation doesn't seem to be needed

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#692]
By only calling receive-invitation on Agent Bob and accept-connection on Agent Alice, the connection still seems to enter completed state.

What is accept-invitation supposed to do?

**Comment by rolsonquadras** [comment]
@troyronda The receive invitation API saves and approves the request in aries-framework-go. The Accept Invitation API is not used. We can either remove or send an error message when this API is invoked.

**Comment by sudeshrshetty** [comment]
@troyronda  Receive invitation usually is 2 step process, (Receive + Accept) unless 'auto accept' is true. 
Receive invitation receives invitation object and later asks business logic's approval to accept it.

Currently we don't support that in REST API, like SDK we handle it like single step process.

**Comment by troyronda** [comment]
FYI @andrewwhitehead @swcurran

**Comment by andrewwhitehead** [comment]
In ACA-py we have the two step process to allow for invitations to be received by different means and create the connection record, while not necessarily invoking any outbound communication. The controller would still receive a webhook and have the chance to accept or remove the new connection (unless auto-accept is enabled, or accept=auto is passed into the receive-invitation method). This matches the pattern used in other protocols where the initial creation of the state record is separate from the triggering of a response (again, unless auto-* is turned on), although in this case the initial trigger isn't received via agent messaging.

I think there might be scenarios where the controller would want to create a new connection record so that related records can be tied to it, before actually accepting the invitation (such as if a proof request needs to be manually authorized first), but that might be a niche use case.
