### ISSUE TITLE
Support HTTP DID Resolver

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#86]
We should allow for resolving DIDs against DID methods that don’t have a Go implementation (or don’t expose a supported interface). Some applications may also benefit by having the DID resolver mechanics separated (Eg., constrained platforms or the need for caches or the need to locally store ledgers).

We should support resolving DIDs via the Universal Resolver Web API
See resolver architecture discussion: https://github.com/hyperledger/aries-rfcs/issues/101#issuecomment-507417223

Reference implementation of a Web Universal Resolver:
https://github.com/decentralized-identity/universal-resolver/tree/master/resolver/java/uni-resolver-web

**Comment by llorllale** [comment]
@troyronda is a universal resolver implementation part of your proposal, or are you suggesting we just connect to https://uniresolver.io/ ?

**Comment by troyronda** [comment]
@llorllale Connect to the API exposed by https://uniresolver.io/ (but the resolver URL can be configured). This proposal is not about building a universal resolver.

**Comment by troyronda** [comment]
* Include mocks of the web resolver API.
* Unit tests against the mock implementation.
* Include a docker-compose integration test and manually test (we will figure out the CI for this integration test later).

**Comment by fqutishat** [comment]
created stories
#99 Create Universal DID Resolver
#100 Create Sidetree DID Resolver
#101 Allow regex expression to resolve did method

**Comment by llorllale** [comment]
Just linking and quoting the rationale that @troyronda exposed [here](https://github.com/hyperledger/aries-framework-go/issues/100#issuecomment-521404557):

> The larger story is to have built-in support DID resolution via Web APIs. We are also planning to support universal resolver (via Web API): #99
> 
> The idea is that we will also have a shortcut for Sidetree (via Web API) to reduce the need for an extra dependency.

**Comment by peacekeeper** [comment]
Hi all, just wanted to say I'd be excited to work with you on resolving DIDs via the Universal Resolver's API. Or more generally, we should talk about resolving DIDs via any compliant service that exposes DID Resolution functionality over the [HTTP(S) binding](https://w3c-ccg.github.io/did-resolution/#bindings-https). The Universal Resolver is just one implementation of this.

+1 to making everything configurable (not locked into the uniresolver.io instance) and +1 to supporting routing of different DID methods (or patterns) to different resolvers.

And in case you're not aware, there is also a proposed [DIDComm binding](https://github.com/hyperledger/aries-rfcs/tree/master/features/0124-did-resolution-protocol) for DID Resolution, i.e. instead of talking to the Universal Resolver via an HTTP(S) API, you could also talk to it via a DIDComm protocol.

We could have a separate call about this if it helps (or just iterate over existing channels).

**Comment by llorllale** [comment]
@peacekeeper thank you for your comments. I've opened #116 for DID resolution using DIDComm.
